version: '3'
services:
  db:
    container_name: boilerplate_postgres_13_2
    image: postgres:13.2
    volumes:
      - ~/storage/boilerplate/postgres:/data/postgres
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: boilerplate_test
      POSTGRES_DB: boilerplate
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: boilerplate
    ports:
      - '5432:5432'

  db_test:
    container_name: boilerplate_postgres_13_2_test
    image: postgres:13.2
    volumes:
      - ~/storage/boilerplate_test/postgres:/data/postgres
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: boilerplate_test
      POSTGRES_DB: boilerplate_test
      POSTGRES_USER: boilerplate_test
      POSTGRES_PASSWORD: boilerplate_test
    ports:
      - '5444:5432'
